# Generated by Django 4.0.6 on 2022-07-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.CharField(blank=True, help_text="Car's model", max_length=250, null=True)),
                ('body_type', models.CharField(choices=[('Hatchback', 'HATCHBACK'), ('Minivan', 'MINIVAN'), ('CrossOverVehicle', 'CROSSOVERVEHICLE'), ('Coupe', 'COUPE'), ('Supercar', 'SUPERCAR'), ('Cabriolet', 'CABRIOLET'), ('Sedan', 'SEDAN'), ('Micro', 'MICRO')], default='Hatchback', max_length=20)),
                ('transmission_type', models.CharField(choices=[('Automation', 'AUTOMATION'), ('Mechanics', 'MECHANICS')], default='Automation', max_length=20)),
                ('color', models.CharField(blank=True, help_text="<b>Car's color</b>", max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=2022, help_text='<b>Year of production</b>', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='<b>The initial price of the car</b>', max_digits=20, null=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
