version: '3.3'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5433:5432
  web:
    build: .
    command: sh -c "
      sleep 10 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery:
    build: .
    command: celery -A internship_car_project worker -B
    volumes:
      - project_data:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - web

  beat:
    build: .
    command: celery -A internship_car_project beat -l INFO
    volumes:
      - project_data:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - celery

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    depends_on:
      - db

  flower:
    build: .
    #    command: flower -A internship_car_project --port=5555 --broker=redis://redis:6379/0
    command: celery -A internship_car_project flower
    ports:
      - "5555:5555"
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - celery
volumes:
  postgres_data:
    driver: local
  project_data: