FROM python:3.9

RUN mkdir -p /usr/src/app/
RUN mkdir -p /usr/src/app/staticfiles/
WORKDIR /usr/src/app/

COPY . /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["sh", "./entrypoint.sh"]