# Generated by Django 4.0.6 on 2022-07-27 10:39

import core.abstract_models
import core.data_and_funcs
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('priorities', models.JSONField(default=core.data_and_funcs.default_showroom_priorities)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'showroom',
            },
        ),
        migrations.CreateModel(
            name='DiscountShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=core.abstract_models.thirty_day_hence)),
                ('amount_of_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('discount_showroom_for_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_car_on_sale', to='car.car', verbose_name='car')),
                ('showrooms_discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_with_discount', to='showroom.showroom', verbose_name='showroom')),
            ],
            options={
                'db_table': 'showroom_discount',
            },
        ),
    ]
