# Generated by Django 4.1 on 2022-08-15 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customeroffer_price_and_more'),
        ('car', '0002_initial'),
        ('showroom', '0002_alter_showroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountshowroom',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_car_with_discount', to='car.car', verbose_name='car'),
        ),
        migrations.AddField(
            model_name='discountshowroom',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='discountshowroom',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_discount', to='showroom.showroom', verbose_name='showroom'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='price_increase',
            field=models.PositiveIntegerField(blank=True, default=13, help_text='<b>The coefficient of price increase</b>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='discountshowroom',
            unique_together={('car', 'showroom')},
        ),
        migrations.RemoveField(
            model_name='discountshowroom',
            name='amount_of_discount',
        ),
        migrations.RemoveField(
            model_name='discountshowroom',
            name='discount_showroom_for_car',
        ),
        migrations.RemoveField(
            model_name='discountshowroom',
            name='showrooms_discount',
        ),
        migrations.CreateModel(
            name='ShowroomLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bought_cars', models.PositiveIntegerField(default=0)),
                ('loyalty_count', models.PositiveIntegerField(default=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_loyalties', to='customer.customer')),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showroom_customer_loyalties', to='showroom.showroom')),
            ],
            options={
                'db_table': 'showroom_loyalty',
                'unique_together': {('customer', 'showroom')},
            },
        ),
    ]
