# Generated by Django 4.0.6 on 2022-07-27 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0002_initial'),
        ('customer', '0001_initial'),
        ('showroom', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromShowroomToCustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_to_customer', to='car.car')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_transaction_history', to='customer.customer')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_that_sells', to='showroom.showroom')),
            ],
            options={
                'db_table': 'transactions_from_showroom_to_customer',
            },
        ),
        migrations.CreateModel(
            name='FromDealerToShowroomTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_for_sale', to='car.car')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_that_sells', to='dealer.dealer')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showroom_that_buys', to='showroom.showroom')),
            ],
            options={
                'db_table': 'transactions_from_dealer_to_showroom',
            },
        ),
    ]
