# Generated by Django 4.1 on 2022-08-08 15:45

import core.data_and_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeroffer',
            name='car',
        ),
        migrations.AddField(
            model_name='customeroffer',
            name='selected_car',
            field=models.JSONField(default=core.data_and_funcs.default_showroom_priorities),
        ),
    ]
