# Generated by Django 4.1 on 2022-08-15 08:25

import core.data_and_funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customeroffer_car_customeroffer_selected_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeroffer',
            name='price',
        ),
        migrations.AlterField(
            model_name='customeroffer',
            name='selected_car',
            field=models.JSONField(default=core.data_and_funcs.default_customer_priorities),
        ),
    ]
