# Generated by Django 4.0.6 on 2022-07-27 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('found_year', models.PositiveIntegerField(blank=True, default=2022, null=True)),
                ('bio', models.TextField(null=True)),
                ('number_of_buyers', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer',
            },
        ),
        migrations.CreateModel(
            name='DiscountDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(choices=[(0, 'Regular Client'), (5, 'Bronze Client'), (7, 'Silver Client'), (10, 'Gold Client'), (15, 'Platinum Client'), (20, 'Diamond Client')], default=0)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_discounts', to='dealer.dealer')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showroom_discounts', to='showroom.showroom')),
            ],
            options={
                'db_table': 'dealer_discount',
                'unique_together': {('showroom', 'dealer')},
            },
        ),
    ]
