# Generated by Django 4.1 on 2022-08-15 08:25

import core.abstract_models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_showroom_user'),
        ('car', '0002_initial'),
        ('dealer', '0002_alter_dealer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountdealer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_dealer_car', to='car.car'),
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='end_date',
            field=models.DateTimeField(default=core.abstract_models.thirty_day_hence),
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='discountdealer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountdealer',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='discountdealer',
            unique_together={('car', 'dealer')},
        ),
        migrations.RemoveField(
            model_name='discountdealer',
            name='showroom',
        ),
        migrations.CreateModel(
            name='DealerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bought_cars', models.PositiveIntegerField(default=0)),
                ('loyalty_count', models.PositiveIntegerField(default=10)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_loyalties', to='dealer.dealer')),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_showroom_loyalties', to='showroom.showroom')),
            ],
            options={
                'db_table': 'dealer_loyalty',
                'unique_together': {('showroom', 'dealer')},
            },
        ),
    ]
